services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend1:
    image: mellow03/backend-presta-banco:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT= ${PORT}
    networks:
      - backend-network

  backend2:
    image: mellow03/backend-presta-banco:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT= ${PORT}
    networks:
      - backend-network

  backend3:
    image: mellow03/backend-presta-banco:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT= ${PORT}
    networks:
      - backend-network

  frontend1:
    image: mellow03/frontend-presta-banco:latest
    networks:
      - frontend-network

  frontend2:
    image: mellow03/frontend-presta-banco:latest
    networks:
      - frontend-network

  frontend3:
    image: mellow03/frontend-presta-banco:latest
    networks:
      - frontend-network

  nginx-frontend:
    image: mellow03/nginx-presta-banco:latest
    ports:
      - "80:80"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  nginx-backend:
    image: mellow03/nginx-presta-banco:latest
    ports:
      - "8081:8081"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  backend-network:
  frontend-network: