pipeline {
    agent any
    tools{
        maven 'maven_3_8_1'
    }
    stages{
        stage('Build maven'){
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Mellowzhong/Tingeso_Lab1/tree/main/Backend']])
                sh 'mvn clean package'
            }
        }

        stage('Build docker image'){
            steps{
                script{
                    sh 'docker build -t mellow03/frontend:latest .'
                }
            }
        }
        stage('Push image to Docker Hub'){
            steps{
                script{
                   withCredentials([string(credentialsId: 'dhpswid', variable: 'dhpsw')]) {
                        sh 'docker login -u mellow03 -p %dhpsw%'
                   }
                   sh 'docker push -t mellow03/frontend:latest .'
                }
            }
        }
    }
}